name: Call a reusable workflow

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  call-workflow:
    uses: polar-bookstore/pipeline-templates/.github/workflows/docker-image.yml@main
    with:
      team: 'klingon-empire'