name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: polar-bookstore/pipeline-templates/.github/workflows/docker-image.yml@v1
    with:
      team: 'klingon-empire'